import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { addListItem, checkListItem, checkoutCart } from "@/app/actions";

export default async function ListDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const session = await auth();
  if (!session?.user?.id) redirect("/signin");
  const { id } = await params;
  const list = await prisma.shoppingList.findFirst({ where: { id, household: { members: { some: { userId: session.user.id } } } }, include: { items: { orderBy: [{ status: "asc" }, { createdAt: "desc" }] }, carts: { where: { status: "ACTIVE" }, include: { items: true }, take: 1 } } });
  if (!list) notFound();
  const openItems = list.items.filter((item) => item.status === "OPEN");
  const cartItems = list.carts[0]?.items ?? [];
  return <main className="app-shell"><header className="topbar"><Link href="/lists" className="wordmark"><span className="brand-mark small">PP</span> pantry pal</Link><div className="topbar-links"><Link href="/lists">All lists</Link><div className="user-chip">{session.user.name?.slice(0, 1) ?? "U"}</div></div></header><div className="detail-wrap"><Link href="/lists" className="back-link">← All lists</Link><div className="detail-heading"><div><p className="eyebrow">SHOPPING LIST</p><h1>{list.name}</h1><p className="muted">{openItems.length} things left to pick up</p></div><div className="list-stats"><strong>{cartItems.length}</strong><span>in cart</span></div></div><form action={addListItem} className="quick-add"><input type="hidden" name="listId" value={id} /><span>＋</span><input name="name" placeholder="Add something to your list..." autoComplete="off" /><button type="submit">Add</button></form><div className="content-columns"><section className="items-panel"><div className="section-label"><span>TO GET</span><span>{openItems.length}</span></div>{openItems.map((item) => <form action={checkListItem} className="item-row" key={item.id}><input type="hidden" name="listId" value={id} /><input type="hidden" name="itemId" value={item.id} /><button type="submit" className="check-button" aria-label={`Move ${item.name} to cart`} /><div className="item-copy"><strong>{item.name}</strong><span>{[item.brand, item.quantity && `${item.quantity} ${item.unit ?? ""}`, item.capacity && `${item.capacity} ${item.capacityUnit ?? ""}`].filter(Boolean).join(" · ") || "No details yet"}</span></div><span className="item-more">···</span></form>)}{openItems.length === 0 && <div className="panel-empty">Everything is in the cart. Nice work.</div>}<div className="section-label completed-label"><span>IN CART</span><span>{cartItems.length}</span></div>{cartItems.map((item) => <div className="item-row checked" key={item.id}><span className="check-button checked-button">✓</span><div className="item-copy"><strong>{item.name}</strong><span>Ready for checkout</span></div></div>)}</section><aside className="cart-card"><div className="cart-card-heading"><div><p className="eyebrow">ACTIVE CART</p><h2>Market run</h2></div><span className="cart-badge">{cartItems.length}</span></div>{cartItems.length ? <><p className="muted">Review details and check out when you’re done shopping.</p><form action={checkoutCart}><input type="hidden" name="listId" value={id} /><input type="hidden" name="cartId" value={list.carts[0]?.id} /><button className="primary-button full" type="submit">Checkout <span>→</span></button></form></> : <div className="cart-empty"><span>🛒</span><p>Check an item to<br />start your cart.</p></div>}</aside></div></div></main>;
}
